Implementação de assinaturas híbridas com a liboqs
PQC-Group-UTFPR/go-std pull request #2
Opened 2024-11-19 00:55 UTC by alexandreboutrik

**Descrição**:
Implementa um sistema de assinaturas híbridas para o projeto [BBPQ](https://pqc-group-utfpr.github.io/projects.html).
@Yuuto-Senpai ficaria encarregado de realizar benchmarks e testes.

**Uso geral**:
1. `GenerateKey`: função para criar uma chave privada;
2. `PrivateKey.ExportPublicKey`: método para extrair a chave pública;
3. `PrivateKey.GetPrivateKeys`: método para obter as chaves públicas clássica e PQC;
5. `PrivateKey.Sign`: método para assinar uma mensagem;
6. `PublicKey.GetPublicKeys`: método para obter as chaves públicas clássica e PQC;
7. `Verify`: função para verificar a validade de uma assinatura híbrida, clássica ou PQC.

**Observações**:
- Segui o modelo de struct utilizado em `crypto/ecdsa` e `crypto/rsa`, onde a struct `PrivateKey` encapsula métodos e mantém uma referência para a struct `PublicKey`. Como a função `GenerateKey` retorna apenas a `PrivateKey`, é necessário utilizar um método `PrivateKey.Export*` para acessar a `PublicKey`.
- A assinatura híbrida é a concatenação das assinaturas clássica e PQC, e ela **não** faz parte das structs, sendo somente passada como argumento e retornada pelos métodos e/ou funções. Não sei se seria interessante armazená-la, criando um novo membro `hybrid []byte` na `PublicKey` ou `PrivateKey`;
- Por estar na codebase da go-std, os commits tentam seguir as convenções definidas pelo CONTRIBUTING.md ao invés da Conventional Commits 1.0.0.

Closes: #1

2024-11-27 13:18 UTC, PQC-Group-UTFPR requested changes
Oi @alexandreboutrik e @Yuuto-Senpai,

segue comentários:
- Sobre a estrutura, eu acho que vale manter desta forma, só peço que deem uma pesquisada sobre as funções de `Marshal` e `Unmarshal` pois talvez precisaremos serializar de alguma forma no futuro.
- Eu só vou pedir uma modificação antes de aprovar, que é em relação aos [comentários imediatamente](https://tip.golang.org/doc/comment) acima das funções, const, pacotes, etc. Em especial comentar que a função `SignASN1` está esperando o hash da mensagem e não a mensagem propriamente dita (correto?). Mesma coisa para a parte PQC.
- E já que pedi modificação para especificar isso, aproveitem para estabelecer a política do `Verify`: verificar ambas obrigatoriamente (i.e., remover o `switch option`).

2024-11-27 14:26 UTC, Yuuto-Senpai commented
Ok.

Em qua., 27 de nov. de 2024, 10:18, Grupo PQC UTFPR-TD <
***@***.***> escreveu:

> ***@***.**** requested changes on this pull request.
>
> Oi @alexandreboutrik <https://github.com/alexandreboutrik> e @Yuuto-Senpai
> <https://github.com/Yuuto-Senpai>,
>
> segue comentários:
>
>    - Sobre a estrutura, eu acho que vale manter desta forma, só peço que
>    deem uma pesquisada sobre as funções de Marshal e Unmarshal pois
>    talvez precisaremos serializar de alguma forma no futuro.
>    - Eu só vou pedir uma modificação antes de aprovar, que é em relação
>    aos comentários imediatamente <https://tip.golang.org/doc/comment>
>    acima das funções, const, pacotes, etc. Em especial comentar que a função
>    SignASN1 está esperando o hash da mensagem e não a mensagem
>    propriamente dita (correto?). Mesma coisa para a parte PQC.
>    - E já que pedi modificação para especificar isso, aproveitem para
>    estabelecer a política do Verify: verificar ambas obrigatoriamente
>    (i.e., remover o switch option).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PQC-Group-UTFPR/go-std/pull/2#pullrequestreview-2465002200>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUSW5WS6ODEP4TFYFCGLRS32CXBDNAVCNFSM6AAAAABSA5BCIKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINRVGAYDEMRQGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-29 19:39 UTC, PQC-Group-UTFPR commented
Aproveitando; alguma chance da estrutura incluir edDSA? Ao invés do ECDSA. Ou criar uma nova. Seria interessante em alguns testes ter o mapeamento do nível um com ed25519 ao invés da P-256.

2024-11-30 02:54 UTC, alexandreboutrik commented
https://github.com/PQC-Group-UTFPR/go-std/pull/2#issuecomment-2508479868 :
> Aproveitando; alguma chance da estrutura incluir edDSA? Ao invés do ECDSA. Ou criar uma nova. Seria interessante em alguns testes ter o mapeamento do nível um com https://github.com/PQC-Group-UTFPR/go-std/commit/ed2551978a9c5037027f96f1658aee307fd5c026 ao invés da P-256.

Acredito que sim, porém não tenho certeza qual seria a forma mais eficiente de se abordar isso. 
O que acha de utilizar polimorfismo com interface{} e type switches, como fiz no commit https://github.com/PQC-Group-UTFPR/go-std/pull/2/commits/3d06b7b273704ffd91d0fc9fb9ca1a0c5797c0bb ? Ou seria melhor criar structs dedicadas para `ecdsa` e `ed25519`?

2024-12-02 18:27 UTC, PQC-Group-UTFPR commented
Sobre o uso de interfaces, Creio que não vai impactar nos benchmarks, talvez um profiling futuro nos dê mais informações. 

Creio que faltou o CROSS com as curvas do NIST (P-256, P-384, P-521) para os parâmetros `small`. Pode adicionar? E aí fechamos a issue.

Obrigado

2024-12-04 22:40 UTC, bifee commented
Adicionado suporte ao algoritmo ML-DSA com ECDSA e ED25519([43f1409](https://github.com/PQC-Group-UTFPR/go-std/pull/2/commits/43f1409f51d2f3883dc30e97f1621f3bedcc6a5b)):
- ML_DSA_44_P256 (lvl 2)
- ML_DSA_65_P384 (lvl 3)
- ML_DSA_87_P521 (lvl 5)
- ML_DSA_65_ED25519 (lvl 3)

Alterado o tipo de retorno de 'GetPublicKeys' e 'GetPrivateKeys' para 'interface{}' para melhorar o polimorfismo.

Closes: #5

2024-12-05 13:13 UTC, PQC-Group-UTFPR commented
Pessoal, uma dúvida:

por que `ed25519.PrivateKey{}` em `var SigOIDtoName = map[OID]SigName{...` ? Se quiser poderia inserir uma string de definição nossa. Se puderem verificar (ou trocar) em todos as ocorrências @alexandreboutrik @bifee

2024-12-26 14:45 UTC, PQC-Group-UTFPR approved these changes

2024-12-26 14:52 UTC, merged